### ISSUE TITLE
invalid url for zlib causes ./Build to fail

### ISSUE THREAD

**Issue by KohaAloha** [PerlGameDev/Alien-SDL2#1]
it looks like the http://www.zlib.net/zlib-1.2.7.tar.gz has gone
but http://www.zlib.net/zlib-1.2.8.tar.gz exists...

do we want to upgrade zlib to 1.2.8, or host 1.2.7 on another server
## error below...

mason@build-32:~/git/Alien-SDL2$ ./Build
Build option used:
        Source code build
    z(v1.2.7) jpeg(v9) png(v1.5.14) freetype(v2.4.11) SDL2(v2.0.0HG) SDL2_image(v2.0.0HG) vorbis(v1.3.3) SDL2_ttf(v2.0.12HG) SDL2_gfx(v20130301-hg) 
Building Alien-SDL2

Do you want to see all messages during configure/make (y/n)? [n ]
n 
Fetching 'http://www.zlib.net/zlib-1.2.7.tar.gz'...
Fetch failed! HTTP response: 404 Not Found [404 Not Found] at inc/My/Builder.pm line 157.
Command failed:  at inc/My/Builder.pm line 157.
Command failed:  at inc/My/Builder.pm line 157.
Got a '404' from 'www.zlib.net' expected '200' at inc/My/Builder.pm line 157.

**Comment by kthakore** [comment]
Can you test this?

**Comment by kthakore** [comment]
Is that good?

**Comment by KohaAloha** [comment]
almost :)

```
the correct sha is 69d42045d87a5e7bff93ae28facb8f448b99b539
```

ps: i can fix this one

**Comment by KohaAloha** [comment]
oops, sorry - my sha was wrong, and yours correct! 

i have fixed this again, with this commit
https://github.com/PerlGameDev/Alien-SDL2/commit/669862ec3597cf6bf5a73334aa15e7d8d6ce1835
