### ISSUE TITLE
Update to libsdl-2.0.1

### ISSUE THREAD

**Issue by Blaizer** [PerlGameDev/Alien-SDL2#5]
When choosing prebuilt binaries or compile from source, the latest version of libsdl should be used. It's currently 2.0.1, while Alien::SDL2 is downloading 2.0.0.

**Comment by FROGGS** [comment]
Hi, for linux you'd just have to add (or update) the cha1sum of the other tarball. For windows we have to prebuild the dlls.

**Comment by Blaizer** [comment]
~~Also note in the latest version -lSDL2main is gone.~~ You now define SDL_MAIN_HANDLED before you include SDL.h, and then call SDL_SetMainReady() before you call SDL_Init().

**Comment by Blaizer** [comment]
Actually I'm not sure about not needing -lSDL2main. But the other thing I said is true.
