### ISSUE TITLE
Don't use $ENV{"HOME"}

### ISSUE THREAD

**Issue by asb-capfan** [PerlGameDev/Alien-SDL2#6]
Hi!

I just installed Alien::SDL2 on my computer and I got the following output:

Set up gcc environment - 3.4.5 (mingw-vista special r3)
Build option used:
        Binaries Win/32bit SDL2 (20130305) RECOMMENDED
        (gfx, image, mixer, net, smpeg, ttf)
Building Alien-SDL2
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at C:/Per
l/lib/CPAN/Config.pm line 6.
Fetching 'http://strawberryperl.com/package/kmx/sdl/32bit_SDL2_20130305.zip'...

There is $ENV{"HOME"}. Is it something that has to do with Alien::SDL2 or is it not related to this module? If it is related, then could we switch to File::HomeDir?

**Comment by kthakore** [comment]
Hi! Hmm weird. Can you set your %home% variable?

**Comment by kthakore** [comment]
Oh right! 

Also hi tobais!!

**Comment by asb-capfan** [comment]
I think I found it. It's as the error states: in CPAN/Config.pm line 6:

my $CPAN_HOME = "$ENV{HOME}/.cpan";
$CPAN_HOME = do {require Config; "$Config::Config{prefix}/cpan"}
    if $^O eq "MSWin32";

But at least kthakore is now File::HomeDir aware :)

**Comment by asb-capfan** [comment]
And it's already fixed in a new version: https://rt.cpan.org/Public/Bug/Display.html?id=17759
All I Need now is a new ActiveState Perl Version...
